### ISSUE TITLE
Prenotazione scheda non dà messaggio di successo

### ISSUE THREAD

**Issue by matteocasonato** [mmatteo23/techweb-lode#18]

**Comment by danilostojkovic** [comment]
e quindi?

**Comment by matteocasonato** [comment]
e quindi fa cagare e bisogna metterlo

**Comment by danilostojkovic** [comment]
Signor Casonato, è pregato di non utilizzare nuovamente questo linguaggio o l'azienda sarà costretta a prendere provvedimenti disciplinari.

**Comment by mmatteo23** [comment]
Signor Stojkovic, mi perplime come lei non abbia compreso quanto richiesto dal suo collega Casonato, sicuramente conseguenza diretta del poco studio e una debole analisi dei requisiti. Per questa volta chiuderemo un occhio.

Buon proseguimento di giornata

Il ven, giu 2459741, AM alle 11:40, Danilo Stojkovic ***@***.***> ha scritto:
